name: expenses_tracker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.11.0
  flutter_svg:
    git:
      url: https://github.com/binSaed/flutter_svg.git
      ref: fix_defs_order
  onboarding: ^3.1.0
  smooth_page_indicator: ^1.0.1
  validators: ^3.0.0
  http: ^0.13.5
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/Onboarding/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.otf
        - asset: assets/fonts/Inter-BlackItalic.otf
        - asset: assets/fonts/Inter-Bold.otf
        - asset: assets/fonts/Inter-BoldItalic.otf
        - asset: assets/fonts/Inter-ExtraBold.otf
        - asset: assets/fonts/Inter-ExtraBoldItalic.otf
        - asset: assets/fonts/Inter-ExtraLight.otf
        - asset: assets/fonts/Inter-ExtraLightItalic.otf
        - asset: assets/fonts/Inter-Italic.otf
        - asset: assets/fonts/Inter-Light.otf
        - asset: assets/fonts/Inter-LightItalic.otf
        - asset: assets/fonts/Inter-Medium.otf
        - asset: assets/fonts/Inter-MediumItalic.otf
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-SemiBold.otf
        - asset: assets/fonts/Inter-SemiBoldItalic.otf
        - asset: assets/fonts/Inter-Thin.otf
        - asset: assets/fonts/Inter-ThinItalic.otf
        - asset: assets/fonts/Inter-V.ttf
          
